In [13]:
import pandas as pd

In [14]:
df_2019 = pd.read_csv("Data/201906-citibike-tripdata.csv")
df_2020 = pd.read_csv("Data/202006-citibike-tripdata.csv")

In [15]:
df_2019.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,330,2019-06-01 00:00:01.5000,2019-06-01 00:05:31.7600,3602,31 Ave & 34 St,40.763154,-73.920827,3570,35 Ave & 37 St,40.755733,-73.923661,20348,Subscriber,1992,1
1,830,2019-06-01 00:00:04.2400,2019-06-01 00:13:55.1470,3054,Greene Ave & Throop Ave,40.689493,-73.942061,3781,Greene Av & Myrtle Av,40.698568,-73.918877,34007,Subscriber,1987,2
2,380,2019-06-01 00:00:06.0190,2019-06-01 00:06:26.7790,229,Great Jones St,40.727434,-73.993790,326,E 11 St & 1 Ave,40.729538,-73.984267,20587,Subscriber,1990,2
3,1155,2019-06-01 00:00:06.7760,2019-06-01 00:19:22.5380,3771,McKibbin St & Bogart St,40.706237,-73.933871,3016,Kent Ave & N 7 St,40.720368,-73.961651,33762,Subscriber,1987,1
4,1055,2019-06-01 00:00:07.5200,2019-06-01 00:17:42.5580,441,E 52 St & 2 Ave,40.756014,-73.967416,3159,W 67 St & Broadway,40.774925,-73.982666,31290,Subscriber,1973,1

In [16]:
df_2020.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1062,2020-06-01 00:00:03.3720,2020-06-01 00:17:46.2080,3419,Douglass St & 4 Ave,40.679279,-73.981540,3419,Douglass St & 4 Ave,40.679279,-73.981540,39852,Customer,1997,2
1,3810,2020-06-01 00:00:03.5530,2020-06-01 01:03:33.9360,366,Clinton Ave & Myrtle Ave,40.693261,-73.968896,336,Sullivan St & Washington Sq,40.730477,-73.999061,37558,Subscriber,1969,0
2,1017,2020-06-01 00:00:09.6140,2020-06-01 00:17:06.8330,389,Broadway & Berry St,40.710446,-73.965251,3562,Classon Ave & St Marks Ave,40.676520,-73.959608,37512,Customer,1988,2
3,226,2020-06-01 00:00:12.1780,2020-06-01 00:03:58.8640,3255,8 Ave & W 31 St,40.750585,-73.994685,505,6 Ave & W 33 St,40.749013,-73.988484,39674,Customer,1969,0
4,1437,2020-06-01 00:00:21.2550,2020-06-01 00:24:18.9650,367,E 53 St & Lexington Ave,40.758281,-73.970694,497,E 17 St & Broadway,40.737050,-73.990093,21093,Customer,1997,2

In [17]:
df_2019["year"] = 2019
df_2020["year"] = 2020

In [18]:
df = df_2019[:250000].append(df_2020[:250000])

In [20]:
df["month"] = "June"

In [21]:
df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,year,month
0,330,2019-06-01 00:00:01.5000,2019-06-01 00:05:31.7600,3602,31 Ave & 34 St,40.763154,-73.920827,3570,35 Ave & 37 St,40.755733,-73.923661,20348,Subscriber,1992,1,2019,June
1,830,2019-06-01 00:00:04.2400,2019-06-01 00:13:55.1470,3054,Greene Ave & Throop Ave,40.689493,-73.942061,3781,Greene Av & Myrtle Av,40.698568,-73.918877,34007,Subscriber,1987,2,2019,June
2,380,2019-06-01 00:00:06.0190,2019-06-01 00:06:26.7790,229,Great Jones St,40.727434,-73.993790,326,E 11 St & 1 Ave,40.729538,-73.984267,20587,Subscriber,1990,2,2019,June
3,1155,2019-06-01 00:00:06.7760,2019-06-01 00:19:22.5380,3771,McKibbin St & Bogart St,40.706237,-73.933871,3016,Kent Ave & N 7 St,40.720368,-73.961651,33762,Subscriber,1987,1,2019,June
4,1055,2019-06-01 00:00:07.5200,2019-06-01 00:17:42.5580,441,E 52 St & 2 Ave,40.756014,-73.967416,3159,W 67 St & Broadway,40.774925,-73.982666,31290,Subscriber,1973,1,2019,June
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,632,2020-06-06 17:06:26.4500,2020-06-06 17:16:59.3430,334,W 20 St & 7 Ave,40.742388,-73.997262,369,Washington Pl & 6 Ave,40.732241,-74.000264,38158,Subscriber,1990,1,2020,June
249996,164,2020-06-06 17:06:27.3270,2020-06-06 17:09:11.4010,3501,E 118 St & Madison Ave,40.801487,-73.944251,3507,Park Ave & E 124 St,40.804555,-73.939686,41465,Subscriber,1986,1,2020,June
249997,801,2020-06-06 17:06:27.6320,2020-06-06 17:19:48.8860,387,Centre St & Chambers St,40.712733,-74.004607,3435,Grand St & Elizabeth St,40.718822,-73.995960,16533,Customer,1969,0,2020,June
249998,916,2020-06-06 17:06:27.6680,2020-06-06 17:21:43.8340,327,Vesey Pl & River Terrace,40.715338,-74.016584,247,Perry St & Bleecker St,40.735354,-74.004831,39574,Customer,1969,0,2020,June
249999,498,2020-06-06 17:06:29.4480,2020-06-06 17:14:47.7130,3453,Devoe St & Lorimer St,40.713352,-73.949103,3077,Stagg St & Union Ave,40.708771,-73.950953,41987,Customer,1969,0,2020,June

In [22]:
df.to_csv("Data/citibike_june_2019_2020.csv")